### ISSUE TITLE
Kod İyileştirmeleri

### ISSUE THREAD

**Issue by barisener** [KaygusuzBK/mirrar-number-checker#5]
- Sayı kontrolünü fonksiyon haline getirip istenilen yerde kullanılabilmelidir.
- Konsol mesajlarının bir objeye atanıp objeden çağırılacak hale getirilmelidir.

Yukarıdaki maddeler ayrı ayrı commitlenecek. Tek bir pr olarak açılacak.

@KaygusuzBK fyi.

**Comment by barisener** [comment]
deneme

**Comment by barisener** [comment]
@KaygusuzBK burayı unutmayalım.

**Comment by KaygusuzBK** [comment]
Ara tatilden sonra hemen

**Comment by barisener** [comment]
@KaygusuzBK son durum nedir ?

**Comment by KaygusuzBK** [comment]
belirli durumlardan ötürü geç başlanıldı .Bugün eski yapılanlara göz atılıp tekrar edildi yarın en geç saat 23.44tde elinizde :)

**Comment by barisener** [comment]
@KaygusuzBK  ??

**Comment by KaygusuzBK** [comment]
Şu an uğraşıyorum

**Comment by barisener** [comment]
@KaygusuzBK burda son durum nedir ? Refactor yapıldı mı kod tarafında ?
